### ISSUE TITLE
Team-based event

### ISSUE THREAD

**Issue by ChrisLane** [nerdhouse/house-issues#10]
I'd like to plan some sort of team-based event that everyone can take part in, possibly something similar to the games night that we had but with captains that pick teams based on pre-planned activities.

Thoughts? Ideas?

**Comment by Precastwig** [comment]
I think we should pick ~4 activities that challenge a variety of skills;

Thrashing everyone at videogames again doesn't seem too interesting to me.

**Comment by literally-dan** [comment]
Cheese and wine eating competition?

**Comment by ChrisLane** [comment]
Ideas:
- Best household item instrument song
- Best cooking blind taste thing

**Comment by literally-dan** [comment]
I assumed this was the cheese and wine night - obviously not?

**Comment by Precastwig** [comment]
***assumption incorrect***
