### ISSUE TITLE
House dinner

### ISSUE THREAD

**Issue by ChrisLane** [nerdhouse/house-issues#11]
We should go out for dinner.

When? Where?

I vote Italian.

**Comment by frebib** [comment]
LGTM

**Comment by mishajw** [comment]
SGTM

**Comment by literally-dan** [comment]
(3 / (2 + 4)) - (3 / 1)
1 + 2
4 / 2
(3 + ((3 / 1) * 2)) - 3
(((2 + 4) - (3 / 1)) * 2) - 3
(((2 + 4) - (3 / 3)) - 1) * 1

**Comment by ChrisLane** [comment]
Might be worth having a vote to kick @darkdan21 out of the house for being a constant troll.

**Comment by literally-dan** [comment]
Fix seems unreliable, reopening as it may need to be reapplied in future.

**Comment by ChrisLane** [comment]
No. no no. no
