### ISSUE TITLE
Watch 'The Pick of Destiny'

### ISSUE THREAD

**Issue by ChrisLane** [nerdhouse/house-issues#12]
@DomWilliams0 has not seen the movie and should. Right @Precastwig?

**Comment by mishajw** [comment]
100%

**Comment by Precastwig** [comment]
All over this

**Comment by frebib** [comment]
For your convenience, it has been added to Plex
https://plex.nerdhouse.io/#!/server/49fb60e11bd25cdddb513ab171dab5986e205e0d/details?key=%2Flibrary%2Fmetadata%2F57868

**Comment by frebib** [comment]
Rock 🤘
