### ISSUE TITLE
Barbecue

### ISSUE THREAD

**Issue by ChrisLane** [nerdhouse/house-issues#14]
We should have a barbecue. Yes.

Issue #13 should be completed first.

**Comment by ChrisLane** [comment]
I made a dope table that's definitely not made out of grocery delivery boxes. #ForTheCause

**Comment by literally-dan** [comment]
BBQ tonight?

**Comment by ChrisLane** [comment]
@darkdan21 Nah, needs to have a date planned further in advance than that.

**Comment by literally-dan** [comment]
We can have more than one!
But just because it's a really nice day!

**Comment by ChrisLane** [comment]
BBQ-1 Complete
