### ISSUE TITLE
Finish final year project report before opening any new issues

### ISSUE THREAD

**Issue by mishajw** [nerdhouse/house-issues#15]

**Comment by ChrisLane** [comment]
Maybe we should finish final year project reports before playing board games too. huh @mishajw !???

**Comment by mishajw** [comment]
All right mister "I spent two hours eating food today"

**Comment by ChrisLane** [comment]
Que?

**Comment by mishajw** [comment]
Stack?

**Comment by frebib** [comment]
And now we may rest
