### ISSUE TITLE
Felix's second job

### ISSUE THREAD

**Issue by mishajw** [nerdhouse/house-issues#8]
Please vote on this issue with the appropriate EmoJiCon.

:+1: for hoovering stairs and landing
:-1: for hoovering kitchen and living room
:smile: the over really needs a clean, seriously it's really grim
:tada: clean Felix's own room
:heart: clean middle floor bathroom

**Comment by ChrisLane** [comment]
Added an option :heart:

**Comment by ChrisLane** [comment]
@darkdan21 @mishajw @DomWilliams0
